### ISSUE TITLE
Query: Can we specify the s3 bucket path of the stack template yaml file in the template: section

### ISSUE THREAD

**Issue by sivaprasad-kiranum** [aws-actions/aws-cloudformation-github-deploy#12]
The CloudFormation stack yaml is hosted in a s3 bucket, can we specify the path of the template in s3:// or http:// format of the. stack.yaml in the template: section?

```yaml
- name: Deploy to AWS CloudFormation
  uses: aws-actions/aws-cloudformation-github-deploy@v1
  with:
    name: MyStack
    template: myStack.yaml
    parameter-overrides: "MyParam1=myValue,MyParam2=${{ secrets.MY_SECRET_VALUE }}"
```
