### ISSUE TITLE
Actions is successful but it doesn't apply the changeset

### ISSUE THREAD

**Issue by AyoubOukh** [aws-actions/aws-cloudformation-github-deploy#122]
Hello, 
We are seeing an issue where the action runs successfully but it doesn't apply the changeset, and therefore the changeset is not deleted - which causes errors in the following deployments: 
`ChangeSet ****-CS cannot be created due to a mismatch with existing attribute Template`
This was quite unclear to debug, but I am positive that the previous run was successful and the changeset wasn't applied, although the CS was successfully created. 
```
      - name: Deploy to AWS CloudFormation
        id: cloudformation_deploy_stacks
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ matrix.pipelines.stack }}
          template: https://s3.amazonaws.com/${{ env.S3_BUCKET }}/${{ matrix.pipelines.stack }}/cfn-template.packaged.yml
          parameter-overrides: file://${{ matrix.pipelines.path }}/config/config.json
          capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
```
