### ISSUE TITLE
Struggling to deploy larger lambda layer

### ISSUE THREAD

**Issue by LoganB99** [aws-actions/aws-cloudformation-github-deploy#133]
Hello, we are moving from Code Pipeline to GitHub Actions, and I am getting a weird error message with a failed deployment step for our lambda layer.

This function's requirements are large, but it is less than 250 MB. the deployment works when I deploy to codepipline

But when we tried our first GHA stack update today (after disabling the flow in pipeline), it failed due to this error

"Resource handler returned message: "Unzipped size must be smaller than 41655897 bytes "

41655897 seems arbitrary. I have seen, and understand, 262144000 bytes. But not this 41655897. 

Anyone have advice, or more information needed?

**Comment by kddejong** [comment]
Is the code in a s3 bucket or is it embedded into the template?  Not that I can make the math work for 41655897 to 4MBs as the limit.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html

**Comment by LoganB99** [comment]
im guessing embedded in the template??, because I don't see where it would be uploaded. the weird thing is, in a working project, I don't see that code either. the only s3 upload or copy command i see is when we s3 cp our lambda authenticator, or when we upload our template.yml

Do you see anything claringly obvious I am missing?

template.yml:

```
MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/myFunction
      Description: "Lambda function to process files"
      FunctionName: !Sub '${myLambdaFunctionName}${sSuffix}'
      Handler: app.lambda_handler
      Runtime: python3.9
      MemorySize: 1000
      Timeout: 300
      Role: !GetAtt IAMRole.Arn
      PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/Boundary"
      Environment:
        Variables:
          BUCKET_NAME: !Sub "${s3BucketName}-${DeployEnvironment}"
          PENDING_S3_LOCATION: "PENDING"
          # PENDING AND OUTPUT WILL BE THE SAME FOR NOW
          OUTPUT_S3_LOCATION: "PENDING"
          LOG_LEVEL: !Ref "logLevel"
      AutoPublishAlias: !Ref FunctionCurrentVersionAlias
      DeploymentPreference:
        Type: !FindInMap [EnvironmentConfiguration, !Ref DeployEnvironment, FunctionDeploymentPreference]
        Role: !GetAtt "IAMRoleForCodeDeploy.Arn"
      Tracing: Active
      PackageType: Zip
      Layers:
        - !Ref MyLayer
        
MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/my_layer
      CompatibleRuntimes:
        - python3.9

```

deployment-actions.yml
```
- name: Setup AWS SAM
      uses: aws-actions/setup-sam@v2
    - name: Installing required dependencies
      run: sh build-scripts/install.sh
    - name: Run AWS SAM Build
      run: sam build --use-container --template-file template.yml
    - name: sam package
      run: sam package --template-file .aws-sam/build/template.yaml --s3-bucket ${{ env.S3_BUCKET }} --output-template-file template.yml --kms-key-id alias/aws/s3

    - name: Upload CloudFormation Template to S3
      run: |
        aws s3 cp ./template.yml s3://${{ env.S3_BUCKET }}/${{ github.event.repository.name }}/template.yml 
        

    - name: Deploy to AWS Cloudformation
# FAILS HERE
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with: 
        name: ${{ github.event.repository.name }}-${{ env.DEPLOYMENT_ENV }}-pipeline-stack-deployment
        template: https://s3.amazonaws.com/${{ env.S3_BUCKET }}/${{ github.event.repository.name }}/template.yml
        parameter-overrides: file://${{ github.workspace }}/params.${{ env.DEPLOYMENT_ENV }}.json
        changeset: --change-set-name
        capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND, CAPABILITY_NAMED_IAM
        no-fail-on-empty-changeset: "1"
        tags: ${{ env.DEPLOYMENT_TAGS }}
```

install.sh:
```
install_dependencies() {
  echo "Installing Node.js code dependencies"
  for function_directory in ${STARTING_DIR}/functions/* ; do
    cd ${function_directory}
    if [ -f "package.json" ]; then
      echo "  Installing dependencies for ${function_directory}"
      npm install
    fi
  done

  echo "Installing Python code dependencies"
  for function_directory in ${STARTING_DIR}/functions/* ; do
    cd ${function_directory}
    if [ -f "requirements.txt" ]; then
      echo "  Installing dependencies for ${function_directory}"
      pip install -r requirements.txt
    fi
  done
}

install_python_layer() {
  LAYER_PATH=${PWD}/python
  echo "  Installing Python layer in ${LAYER_PATH}"

  cd ${LAYER_PATH}
  if [ -f "requirements.txt" ]; then
    pip install -r requirements.txt -t . --upgrade
  fi

  if [ "${PYTHONPATH#*LAYER_PATH}" = "${PYTHONPATH}" ]; then
    if [ "${PYTHONPATH}" = "" ]; then
      export PYTHONPATH=${LAYER_PATH}
    else
      export PYTHONPATH=${LAYER_PATH}:${PYTHONPATH}
    fi
  fi
}

install_nodejs_layer() {
  LAYER_PATH=${PWD}/nodejs
  NODE_MODULES_DIR=${LAYER_PATH}/node_modules
  echo "  Installing NodeJS layer in ${LAYER_PATH}"

  cd ${LAYER_PATH}
  if [ -f "package.json" ]; then
    npm install
  fi

  if [ "${NODE_PATH#*$LAYER_PATH}" = "${NODE_PATH}" ]; then
   if [ "$NODE_PATH" = "" ]; then
     export NODE_PATH=${NODE_MODULES_DIR}
   else
     export NODE_PATH=${NODE_MODULES_DIR}:${NODE_PATH}
   fi
  fi
}

install_layers() {
  echo "Installing Lambda layers"
  for layer_directory in ${STARTING_DIR}/layers/*; do
    cd ${layer_directory}
    if [ -d "python" ]; then
      install_python_layer
    elif [ -d "nodejs" ]; then
      install_nodejs_layer
    fi
  done
  echo "NODE_PATH=${NODE_PATH}"
  echo "PYTHONPATH=${PYTHONPATH}"
}

echo "Starting install - $(date)"
STARTING_DIR=$PWD
set -xe


install_dependencies
install_layers

cd $STARTING_DIR
unset STARTING_DIR
echo "Completed install - $(date)"
```
