### ISSUE TITLE
Allow no capabilities when performing action

### ISSUE THREAD

**Issue by joshuadschoep** [aws-actions/aws-cloudformation-github-deploy#134]
Hi all,

I'm hoping to be able to create and deploy stack that explicitly does not allow IAM capabilities, even unnamed roles. We'd like to be able to explicitly define those elsewhere in our CF stacks.

Leaving an empty list for the capabilities parameter:
```
with:
  name: Web-Frontend
  ...
  no-fail-on-empty-changeset: "1"
  capabilities: # Nothing here to explicitly disallow capabilities
```
throws the following error.
`1 validation error detected: Value '[]' at 'capabilities' failed to satisfy constraint: Member must satisfy constraint: [Member must satisfy enum value set: [CAPABILITY_AUTO_EXPAND, CAPABILITY_NAMED_IAM, CAPABILITY_IAM]]`

I'm hoping I'm going about things wrong, but if not would like to put this in as a feature request.

Thanks a ton!
