### ISSUE TITLE
no-fail-on-empty-changeset doesn't seem to work

### ISSUE THREAD

**Issue by Janpot** [aws-actions/aws-cloudformation-github-deploy#14]
I'm getting these errors:

<img width="646" alt="Screenshot 2020-05-27 at 16 52 06" src="https://user-images.githubusercontent.com/2109932/83036049-7d5cc300-a03a-11ea-933d-17d1410978cf.png">

Could it be that [this check](https://github.com/aws-actions/aws-cloudformation-github-deploy/blob/fad74716082f748c6a6466b3cb16802d92e2b8fe/src/deploy.ts#L36) is insufficient?

**Comment by katallaxie** [comment]
@Janpot could please change the config to `no-fail-on-empty-changeset: "1"` so making this explicitly a string. Please see the `actions.yaml` for this.

**Comment by Janpot** [comment]
@katallaxie I've already configured it that way, this screenshot is how that's printed by the github action

**Comment by katallaxie** [comment]
Just wanted to make sure the configuration is not an issue. Just tested end to end with the following config

```yaml
- name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: TestStack
        template: template.yaml
        parameter-overrides: "KeyName=MyKey"
        tags: "[{\"Key\":\"MyTag\",\"Value\":\"MyValue\"}]"
        no-fail-on-empty-changeset: "1"
        disable-rollback: "0"
```
and failed to reproduce. Can you provide some further information,

**Comment by Janpot** [comment]
```yml
    - name: Deploy synthetics tests
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: synthetics-prod
        template: ./stack.json
        no-fail-on-empty-changeset: "1"
```

It looks like it could be caused by rerunning jobs.
First time this action runs it succeeds in updating the stack in cloudformation, I can verify this in the AWS console. If I rerun the jobs by selecting "Re-run jobs > Re-run all jobs" in the Github UI I get
<img width="531" alt="Screenshot 2020-05-27 at 18 26 51" src="https://user-images.githubusercontent.com/2109932/83046955-05959500-a048-11ea-940c-832e2f20e301.png">
While nothing shows in the event log for this stack. Third time I run this job I get
<img width="585" alt="Screenshot 2020-05-27 at 18 28 20" src="https://user-images.githubusercontent.com/2109932/83047121-3b3a7e00-a048-11ea-93cd-98941819a9cb.png">
and then every subsequent rerun of these jobs it alternates between these two errors.

Can you try rerunning your action to see if that triggers it?

**Comment by katallaxie** [comment]
So, what I tested is the following.

1. Updated the Stack with a new resource
2. Triggered a manual re-run of the workflow

This worked. Could it be that you run jobs in parallel? Because it seems that the Change Set is not in the right state `CREATE_COMPLETE` with the first error. While the second error is mysterious, because this should actually prevented. I will see if we can add more debug information.

**Comment by Janpot** [comment]
This is what I see in the AWS console for the state of this changeset when I get the error"Resource is not in the statechangeSetCreateComplete":

<img width="692" alt="Screenshot 2020-05-27 at 20 46 24" src="https://user-images.githubusercontent.com/2109932/83060067-2b786500-a05b-11ea-8bf5-1b0d8c6f4964.png">

The second time around when I get the other error, that changeSet is deleted again. That's why it cycles between the two errors.

I ran into this thread which seems to talk about similar issues https://github.com/aws/aws-vsts-tools/issues/97 and they seem to have solved it by taking both error messages into account as can be seen in this PR https://github.com/aws/aws-vsts-tools/commit/e90cd7190bc6c9fd1522008c553d41cd688ed4db

**Comment by katallaxie** [comment]
@Janpot can you test this with the `not-fail-on-updates-14` branch as follows.

```yaml
- name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@not-fail-on-updates-14
      with:
        name: TestStack
        template: template.yaml
        no-fail-on-empty-changeset: "1"
        disable-rollback: "0"
```
