### ISSUE TITLE
Using parameter-overrides requires CAPABILITY_AUTO_EXPAND when expanding secrets

### ISSUE THREAD

**Issue by janmiderback** [aws-actions/aws-cloudformation-github-deploy#15]
It was not obvious to me, but it seems as if

```yaml
with:
  name: MyStack
  template: myStack.yaml
  parameter-overrides: "MyParam1=myValue,MyParam2=${{ secrets.MY_SECRET_VALUE }}"
```

requires that you also set `capabilities` to include `CAPABILITY_AUTO_EXPAND`. It is not clear from the documentation.

Otherwise, really enjoy trying this out for our pipeline :+1:
