### ISSUE TITLE
TemplateURL with Nested Stacks is not updated

### ISSUE THREAD

**Issue by dkhmelenko** [aws-actions/aws-cloudformation-github-deploy#32]
I'm getting the following error `TemplateURL must be an Amazon S3 URL.` whenever I'm using a nested stack. 

My root stack looks like this
```yml
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Root stack template'
Resources:
  ObjectStorageStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: 'object_storage_template.yml'
```

And nested stack is in file `object_storage_template.yml`
```yml
Resources:
    ObjectBucket:
      Type: AWS::S3::Bucket
```

I would expect that this deploy action performs packaging and therefore the `TemplateURL` gets updated. 

Is this behavior supported by this action?
