### ISSUE TITLE
Invalid input for parameter key file://***.json. Need to specify either usePreviousValue as true or a value for the parameter

### ISSUE THREAD

**Issue by javs-perez** [aws-actions/aws-cloudformation-github-deploy#39]
When using `parameter-overrides` and passing in a file. I get the following error:

`Invalid input for parameter key file://***/***.json. Need to specify either usePreviousValue as true or a value for the parameter`

The job in the workflow looks as follows:

```
    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: XYXYXYXY
        template: ******.yaml
        parameter-overrides: file://***/***.json
        no-fail-on-empty-changeset: "1"
        capabilities: CAPABILITY_NAMED_IAM
        tags: ${{ env.STACK_TAGS }}
```

The parameter file has the following format: 

```
[
  {
    "ParameterKey": "Env",
    "ParameterValue": "XYXYXYX"
  },
  {
    "ParameterKey": "RepoName",
    "ParameterValue": "XYXYXYX"
  }
]
```

We are following the current instructions from `actions.yml`:

```
  parameter-overrides:
    description: 'The parameters to override in the stack inputs. You can pass a comma-delimited list or a local JSON file. Comma-delimited list has each entry formatted as <ParameterName>=<ParameterValue>. A local JSON file should be named with "file://" prefix (e.g. file://params.json) and should look like: [ { "ParameterKey": "KeyPairName", "ParameterValue": "MyKey" }]'
    required: false
```

**Comment by katallaxie** [comment]
Hi, could it be the case that you updated the parameter value or do not provide a value for the parameter this updated in the stack? Have a look for [UsePreviousValue](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Parameter.html) on the stack update.

**Comment by javs-perez** [comment]
Hi @katallaxie, I'm not sure. We are not using `UsePreviousValue`.

When I passed the same parameters that were in the `***.json` file as just a string in the following format, it worked fine.

```
    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: XYXYXYXY
        template: ******.yaml
        no-fail-on-empty-changeset: "1"
        capabilities: CAPABILITY_NAMED_IAM
        tags: ${{ env.STACK_TAGS }}
        parameter-overrides: >-
          ENV=XYXYXYX,
          RepoName=XYXYXYX
```
