### ISSUE TITLE
'no-delete-failed-changeset' and 'no-execute-changeset' not recognised as valid inputs

### ISSUE THREAD

**Issue by ruthwells** [aws-actions/aws-cloudformation-github-deploy#40]
When I use the following in my workflow, following the instructions [here](https://github.com/marketplace/actions/aws-cloudformation-deploy-cloudformation-stack-action-for-github-actions)

```
    - id: deploy
      name: AWS CloudFormation "Deploy CloudFormation Stack" Action for GitHub Actions
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ${{ steps.stackname.outputs.stackname }}
        template: ${{ steps.filename.outputs.filename }}
        no-delete-failed-changeset: "1"
        no-execute-changeset: "1"
        no-fail-on-empty-changeset: "1"
```
I get a warning when the action executes: 

`##[warning]Unexpected input(s) 'no-delete-failed-changeset', 'no-execute-changeset', valid inputs are ['name', 'template', 'capabilities', 'parameter-overrides', 'no-fail-on-empty-changeset', 'disable-rollback', 'timeout-in-minutes', 'notification-arns', 'role-arn', 'tags', 'termination-protection']`

The changeset is created and visible in the console, but the action is clearly still trying to deploy it, as the action then fails since I have (intentionally) not yet set the IAM permissions to actually deploy the changeset (in this case to create a hosted zone) with the following error in the cloudformation console: 

`API: route53:CreateHostedZone User: arn:aws:iam::<my-user-arn> is not authorized to perform: route53:CreateHostedZone
`

And once the deploy has failed, the changeset then deletes too, and is no longer visible.

I must be missing something somewhere, but I can't see what!
