### ISSUE TITLE
ParameterOverrides with commas in them fail

### ISSUE THREAD

**Issue by damian-bisignano** [aws-actions/aws-cloudformation-github-deploy#47]
I've got a parameter that is a comma separated list. this doesn't work it instead splits on this value, expecting it to be another Key-Value pair

i've tried with all sorts of combinations of " and ' around the parameters and couldn't get it working.

```
env:
  SECURITY_GROUP_ID: sg-11111111
  SUBNET_ID: subnet-11111111,subnet-22222222

      - name: Deploy to AWS CloudFormation
        id: cloudformation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: MyStack
          template: ./infrastructure.json
          parameter-overrides: >-
            SecurityGroupId=${{ env.SECURITY_GROUP_ID }},
            SubnetId=${{ env.SUBNET_ID }}
```

the error i get is

Error: Invalid input for parameter key subnet-22222222". Need to specify either usePreviousValue as true or a value for the parameter

I imagine the update just needs to be update src/utils.ts line 52 to update to a regex that ignores if you have an escape character before the comma
