### ISSUE TITLE
Allow inclusion of stack policy when deploying

### ISSUE THREAD

**Issue by olivermarkrichman** [aws-actions/aws-cloudformation-github-deploy#56]
I'm trying to deploy using this action but if for whatever reason my stack fails and the stack is rolled back I want to be able to update which is why I usually have a cloudformation stack policy. There doesn't seem to be any way to provide a policy when deploying using the action. Could this feature get introduced please?

```
- name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: My-Stack-Name
          template: ${{ github.workspace}}/cloudformation.yml
```
