### ISSUE TITLE
Deploying ECS stack

### ISSUE THREAD

**Issue by codeguru42** [aws-actions/aws-cloudformation-github-deploy#75]
I get the following error when deploying my ECS cluster:

> Error: ENOENT: no such file or directory, open '/home/runner/work/go-capture-api/go-capture-api/cloud-formation/ecs.yml'

My `deploy.yml` file is as follows:

```
name: Deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::200049542062:role/gocapture/GithubRole
          aws-region: us-west-1

      - name: Deploy ECS Cluster
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: GoCaptureECSCluster
          template: cloud-formation/ecs.yml
          no-fail-on-empty-changeset: 1
```

As you can see the name of my repository is repeated in the path. Why is this? What am I missing?

You can find the job here: https://github.com/codeguru42/go-capture-api/actions/runs/3633130293/attempts/1
