### ISSUE TITLE
Error: File URL host must be "localhost" or empty on linux

### ISSUE THREAD

**Issue by georgeismike** [aws-actions/aws-cloudformation-github-deploy#78]
I am trying to pass in a file for the Parameter Overrides below.  When doing it I get:

**Error: File URL host must be "localhost" or empty on linux**

```
      - name: Deploy ECR Cloudformation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ secrets.ENV_NAME }}-ecr-repos \
          template: ./devops/ecs/ecr_repos.yml
          no-fail-on-empty-changeset: "1"
          region: ${{ env.REGION }}
          parameter-overrides: file://devops/config/cluster/ecr/${{ secrets.ENV_NAME }}.json
```

Using the AWS CLI works fine:

````
      - name: ECR Repository Setup
        run: |
          aws cloudformation deploy \
            --capabilities CAPABILITY_NAMED_IAM \
            --template-file ./devops/ecs/ecr_repos.yml \
            --no-fail-on-empty-changeset \
            --stack-name ${{ secrets.ENV_NAME }}-ecr-repos \
            --region ${{ env.REGION }} \
            --parameter-overrides \
            file://devops/config/cluster/ecr/${{ secrets.ENV_NAME }}.json
```

I am sure I am doing something wrong but I can't figure it out.  I have tried hardcoding an ENV_NAME in case it was an interpolation issue.  

Thanks for any suggestions.
