### ISSUE TITLE
Specifying values for "capabilities" parameter?

### ISSUE THREAD

**Issue by lamontadams** [aws-actions/aws-cloudformation-github-deploy#93]
Hi there. I have a template that creates some IAM objects, and I apparently need to specify `--capabilities CAPABILITY_IAM` but I'm not clear on how to do this or if it's even possible. I have tried: 

```
name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: stack-name
          template: master-packaged.template.json
          parameter-overrides: >-
               capabilities=CAPABILITY_IAM
```

and 

```
name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: stack-name
          template: master-packaged.template.json
          parameter-overrides: >-
               Capabilities=CAPABILITY_IAM
```

and also created a `parameters.json` file containing 
```
[
	{
	  "ParameterKey": "Capabilities",
	  "ParameterValue": "CAPABILITY_IAM"
	}
]
```
and this action:
```
name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: stack-name
          template: master-packaged.template.json
          parameter-overrides: >-
               [Capabilities=CAPABILITY_IAM](parameter-overrides: "file://${{ github.workspace }}/parameters.json")
```

In all cases the action fails and I get this error:

`Error: Parameters: [Capabilities] do not exist in the template`

Am I barking up the wrong tree here?

**Comment by hasanasim** [comment]
Hi Lamont, 

You can specify capabilities at the same level as `parameter-overrides` with a comma delimited list

```
name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: stack-name
          template: master-packaged.template.json
          capabilities: CAPABILITY_IAM, CAPABILITY_NAMED_IAM
```
